language: vala
compiler:
  - vala
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:inizan-yannick/development
  - sudo apt-get update -qq
  - sudo apt-get install valac-0.24 libgee-0.8-dev gobject-introspection
script: ./autogen.sh && make && make install
notifications:
  irc:
    channels:
      - "irc.freenode.org#canaldev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
