language: vala
compiler:
  - vala
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update -qq
  - sudo apt-get install valac-0.26 gobject-introspection libmagic-dev
script: ./autogen.sh && make && sudo make install
notifications:
  irc:
    channels:
      - "irc.freenode.net#canaldev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
