/* my.dictionary.c generated by valac 0.20.0, the Vala compiler
 * generated from my.dictionary.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define MY_TYPE_IDICTIONARY (my_idictionary_get_type ())
#define MY_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_IDICTIONARY, MyIDictionary))
#define MY_IS_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_IDICTIONARY))
#define MY_IDICTIONARY_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_IDICTIONARY, MyIDictionaryIface))

typedef struct _MyIDictionary MyIDictionary;
typedef struct _MyIDictionaryIface MyIDictionaryIface;

#define MY_TYPE_ILIST (my_ilist_get_type ())
#define MY_ILIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ILIST, MyIList))
#define MY_IS_ILIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ILIST))
#define MY_ILIST_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_ILIST, MyIListIface))

typedef struct _MyIList MyIList;
typedef struct _MyIListIface MyIListIface;

#define MY_TYPE_DICTIONARY (my_dictionary_get_type ())
#define MY_DICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_DICTIONARY, MyDictionary))
#define MY_DICTIONARY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_TYPE_DICTIONARY, MyDictionaryClass))
#define MY_IS_DICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_DICTIONARY))
#define MY_IS_DICTIONARY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_TYPE_DICTIONARY))
#define MY_DICTIONARY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_TYPE_DICTIONARY, MyDictionaryClass))

typedef struct _MyDictionary MyDictionary;
typedef struct _MyDictionaryClass MyDictionaryClass;
typedef struct _MyDictionaryPrivate MyDictionaryPrivate;

#define MY_TYPE_LIST (my_list_get_type ())
#define MY_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_LIST, MyList))
#define MY_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_TYPE_LIST, MyListClass))
#define MY_IS_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_LIST))
#define MY_IS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_TYPE_LIST))
#define MY_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_TYPE_LIST, MyListClass))

typedef struct _MyList MyList;
typedef struct _MyListClass MyListClass;

#define MY_TYPE_ENTRY (my_entry_get_type ())
#define MY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ENTRY, MyEntry))
#define MY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_TYPE_ENTRY, MyEntryClass))
#define MY_IS_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ENTRY))
#define MY_IS_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_TYPE_ENTRY))
#define MY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_TYPE_ENTRY, MyEntryClass))

typedef struct _MyEntry MyEntry;
typedef struct _MyEntryClass MyEntryClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _my_entry_unref0(var) ((var == NULL) ? NULL : (var = (my_entry_unref (var), NULL)))

struct _MyIListIface {
	GTypeInterface parent_iface;
	gpointer (*get) (MyIList* self, gint index);
	void (*set) (MyIList* self, gint index, gconstpointer val);
	void (*add) (MyIList* self, gconstpointer item);
	void (*add_range) (MyIList* self, gpointer* items, int items_length1);
	void (*add_collection) (MyIList* self, MyIList* coll);
	gboolean (*contains) (MyIList* self, gconstpointer item);
	void (*insert) (MyIList* self, gint position, gconstpointer item);
	void (*insert_all) (MyIList* self, gint position, gpointer* items, int items_length1);
	void (*insert_collection) (MyIList* self, gint position, MyIList* coll);
	void (*reverse) (MyIList* self);
	gint (*index_of) (MyIList* self, gconstpointer item);
	gint* (*index_of_all) (MyIList* self, gconstpointer item, int* result_length1);
	void (*remove) (MyIList* self, gconstpointer item);
	void (*remove_at) (MyIList* self, gint index);
	void (*remove_all) (MyIList* self, gconstpointer item);
	void (*remove_range) (MyIList* self, gint start, gint length);
	gint (*get_size) (MyIList* self);
};

struct _MyIDictionaryIface {
	GTypeInterface parent_iface;
	void (*add) (MyIDictionary* self, gconstpointer key, gconstpointer val);
	gpointer (*get) (MyIDictionary* self, gconstpointer key);
	void (*set) (MyIDictionary* self, gconstpointer key, gconstpointer val);
	gboolean (*unset) (MyIDictionary* self, gconstpointer key, gpointer* val);
	gboolean (*has_key) (MyIDictionary* self, gconstpointer key);
	gboolean (*has_value) (MyIDictionary* self, gconstpointer val);
	MyIList* (*get_keys) (MyIDictionary* self);
	MyIList* (*get_values) (MyIDictionary* self);
	gint (*get_size) (MyIDictionary* self);
};

struct _MyDictionary {
	GObject parent_instance;
	MyDictionaryPrivate * priv;
};

struct _MyDictionaryClass {
	GObjectClass parent_class;
};

struct _MyDictionaryPrivate {
	GType k_type;
	GBoxedCopyFunc k_dup_func;
	GDestroyNotify k_destroy_func;
	GType v_type;
	GBoxedCopyFunc v_dup_func;
	GDestroyNotify v_destroy_func;
	GEqualFunc kf;
	GEqualFunc vf;
	MyList* _keys;
	MyList* _values;
	MyList* _entries;
};


static gpointer my_dictionary_parent_class = NULL;
static MyIDictionaryIface* my_dictionary_my_idictionary_parent_iface = NULL;

GType my_ilist_get_type (void) G_GNUC_CONST;
GType my_idictionary_get_type (void) G_GNUC_CONST;
GType my_dictionary_get_type (void) G_GNUC_CONST;
GType my_list_get_type (void) G_GNUC_CONST;
gpointer my_entry_ref (gpointer instance);
void my_entry_unref (gpointer instance);
GParamSpec* my_param_spec_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void my_value_set_entry (GValue* value, gpointer v_object);
void my_value_take_entry (GValue* value, gpointer v_object);
gpointer my_value_get_entry (const GValue* value);
GType my_entry_get_type (void) G_GNUC_CONST;
#define MY_DICTIONARY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MY_TYPE_DICTIONARY, MyDictionaryPrivate))
enum  {
	MY_DICTIONARY_DUMMY_PROPERTY,
	MY_DICTIONARY_K_TYPE,
	MY_DICTIONARY_K_DUP_FUNC,
	MY_DICTIONARY_K_DESTROY_FUNC,
	MY_DICTIONARY_V_TYPE,
	MY_DICTIONARY_V_DUP_FUNC,
	MY_DICTIONARY_V_DESTROY_FUNC,
	MY_DICTIONARY_KEYS_FUNC,
	MY_DICTIONARY_VALUES_FUNC,
	MY_DICTIONARY_KEYS,
	MY_DICTIONARY_VALUES,
	MY_DICTIONARY_SIZE,
	MY_DICTIONARY_ENTRIES
};
MyDictionary* my_dictionary_new (GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, GEqualFunc key_equal, GEqualFunc value_equal);
MyDictionary* my_dictionary_construct (GType object_type, GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, GEqualFunc key_equal, GEqualFunc value_equal);
GEqualFunc my_functions_equal_func_for (GType t);
MyList* my_list_new (GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, GEqualFunc func, GCompareFunc cfunc);
MyList* my_list_construct (GType object_type, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, GEqualFunc func, GCompareFunc cfunc);
static void my_dictionary_real_add (MyIDictionary* base, gconstpointer key, gconstpointer val);
void my_ilist_add (MyIList* self, gconstpointer item);
static gpointer my_dictionary_real_get (MyIDictionary* base, gconstpointer key);
gint my_ilist_index_of (MyIList* self, gconstpointer item);
gpointer my_ilist_get (MyIList* self, gint index);
static void my_dictionary_real_set (MyIDictionary* base, gconstpointer key, gconstpointer val);
void my_idictionary_add (MyIDictionary* self, gconstpointer key, gconstpointer val);
void my_ilist_set (MyIList* self, gint index, gconstpointer val);
static gboolean my_dictionary_real_unset (MyIDictionary* base, gconstpointer key, gpointer* val);
gboolean my_idictionary_has_key (MyIDictionary* self, gconstpointer key);
void my_ilist_remove_at (MyIList* self, gint index);
static gboolean my_dictionary_real_has_key (MyIDictionary* base, gconstpointer key);
gboolean my_ilist_contains (MyIList* self, gconstpointer item);
static gboolean my_dictionary_real_has_value (MyIDictionary* base, gconstpointer val);
GEqualFunc my_dictionary_get_keys_func (MyDictionary* self);
GEqualFunc my_dictionary_get_values_func (MyDictionary* self);
gint my_ilist_get_size (MyIList* self);
MyIList* my_dictionary_get_entries (MyDictionary* self);
gint my_idictionary_get_size (MyIDictionary* self);
MyIList* my_idictionary_get_keys (MyIDictionary* self);
MyIList* my_idictionary_get_values (MyIDictionary* self);
MyEntry* my_entry_new (GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, gconstpointer k, gconstpointer v);
MyEntry* my_entry_construct (GType object_type, GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, gconstpointer k, gconstpointer v);
static void my_dictionary_finalize (GObject* obj);
static void _vala_my_dictionary_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_my_dictionary_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


MyDictionary* my_dictionary_construct (GType object_type, GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, GEqualFunc key_equal, GEqualFunc value_equal) {
	MyDictionary * self = NULL;
	GEqualFunc _tmp0_;
	GEqualFunc _tmp1_;
	GEqualFunc _tmp2_;
	GEqualFunc _tmp4_;
	MyList* _tmp6_;
	MyList* _tmp7_;
	MyList* _tmp8_;
	self = (MyDictionary*) g_object_new (object_type, NULL);
	self->priv->k_type = k_type;
	self->priv->k_dup_func = k_dup_func;
	self->priv->k_destroy_func = k_destroy_func;
	self->priv->v_type = v_type;
	self->priv->v_dup_func = v_dup_func;
	self->priv->v_destroy_func = v_destroy_func;
	_tmp0_ = key_equal;
	self->priv->kf = _tmp0_;
	_tmp1_ = value_equal;
	self->priv->vf = _tmp1_;
	_tmp2_ = key_equal;
	if (_tmp2_ == NULL) {
		GEqualFunc _tmp3_ = NULL;
		_tmp3_ = my_functions_equal_func_for (k_type);
		self->priv->kf = _tmp3_;
	}
	_tmp4_ = value_equal;
	if (_tmp4_ == NULL) {
		GEqualFunc _tmp5_ = NULL;
		_tmp5_ = my_functions_equal_func_for (v_type);
		self->priv->vf = _tmp5_;
	}
	_tmp6_ = my_list_new (k_type, (GBoxedCopyFunc) k_dup_func, k_destroy_func, NULL, NULL);
	_g_object_unref0 (self->priv->_keys);
	self->priv->_keys = _tmp6_;
	_tmp7_ = my_list_new (v_type, (GBoxedCopyFunc) v_dup_func, v_destroy_func, NULL, NULL);
	_g_object_unref0 (self->priv->_values);
	self->priv->_values = _tmp7_;
	_tmp8_ = my_list_new (MY_TYPE_ENTRY, (GBoxedCopyFunc) my_entry_ref, my_entry_unref, NULL, NULL);
	_g_object_unref0 (self->priv->_entries);
	self->priv->_entries = _tmp8_;
	return self;
}


MyDictionary* my_dictionary_new (GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, GEqualFunc key_equal, GEqualFunc value_equal) {
	return my_dictionary_construct (MY_TYPE_DICTIONARY, k_type, k_dup_func, k_destroy_func, v_type, v_dup_func, v_destroy_func, key_equal, value_equal);
}


static void my_dictionary_real_add (MyIDictionary* base, gconstpointer key, gconstpointer val) {
	MyDictionary * self;
	gconstpointer _tmp0_;
	MyList* _tmp1_;
	gconstpointer _tmp2_;
	MyList* _tmp3_;
	gconstpointer _tmp4_;
	self = (MyDictionary*) base;
	_tmp0_ = key;
	if (_tmp0_ == NULL) {
		return;
	}
	_tmp1_ = self->priv->_keys;
	_tmp2_ = key;
	my_ilist_add ((MyIList*) _tmp1_, _tmp2_);
	_tmp3_ = self->priv->_values;
	_tmp4_ = val;
	my_ilist_add ((MyIList*) _tmp3_, _tmp4_);
}


static gpointer my_dictionary_real_get (MyIDictionary* base, gconstpointer key) {
	MyDictionary * self;
	gpointer result = NULL;
	MyList* _tmp0_;
	gconstpointer _tmp1_;
	gint _tmp2_ = 0;
	gint pos;
	gint _tmp3_;
	MyList* _tmp4_;
	gint _tmp5_;
	gpointer _tmp6_ = NULL;
	self = (MyDictionary*) base;
	_tmp0_ = self->priv->_keys;
	_tmp1_ = key;
	_tmp2_ = my_ilist_index_of ((MyIList*) _tmp0_, _tmp1_);
	pos = _tmp2_;
	_tmp3_ = pos;
	if (_tmp3_ == (-1)) {
		result = NULL;
		return result;
	}
	_tmp4_ = self->priv->_values;
	_tmp5_ = pos;
	_tmp6_ = my_ilist_get ((MyIList*) _tmp4_, _tmp5_);
	result = _tmp6_;
	return result;
}


static void my_dictionary_real_set (MyIDictionary* base, gconstpointer key, gconstpointer val) {
	MyDictionary * self;
	MyList* _tmp0_;
	gconstpointer _tmp1_;
	gint _tmp2_ = 0;
	gint pos;
	gint _tmp3_;
	self = (MyDictionary*) base;
	_tmp0_ = self->priv->_keys;
	_tmp1_ = key;
	_tmp2_ = my_ilist_index_of ((MyIList*) _tmp0_, _tmp1_);
	pos = _tmp2_;
	_tmp3_ = pos;
	if (_tmp3_ == (-1)) {
		gconstpointer _tmp4_;
		gconstpointer _tmp5_;
		_tmp4_ = key;
		_tmp5_ = val;
		my_idictionary_add ((MyIDictionary*) self, _tmp4_, _tmp5_);
	} else {
		MyList* _tmp6_;
		gint _tmp7_;
		gconstpointer _tmp8_;
		_tmp6_ = self->priv->_values;
		_tmp7_ = pos;
		_tmp8_ = val;
		my_ilist_set ((MyIList*) _tmp6_, _tmp7_, _tmp8_);
	}
}


static gboolean my_dictionary_real_unset (MyIDictionary* base, gconstpointer key, gpointer* val) {
	MyDictionary * self;
	gpointer _vala_val = NULL;
	gboolean result = FALSE;
	gconstpointer _tmp0_;
	gboolean _tmp1_ = FALSE;
	self = (MyDictionary*) base;
	_tmp0_ = key;
	_tmp1_ = my_idictionary_has_key ((MyIDictionary*) self, _tmp0_);
	if (_tmp1_) {
		MyList* _tmp2_;
		gconstpointer _tmp3_;
		gint _tmp4_ = 0;
		gint i;
		MyList* _tmp5_;
		gint _tmp6_;
		MyList* _tmp7_;
		gint _tmp8_;
		gpointer _tmp9_ = NULL;
		MyList* _tmp10_;
		gint _tmp11_;
		_tmp2_ = self->priv->_keys;
		_tmp3_ = key;
		_tmp4_ = my_ilist_index_of ((MyIList*) _tmp2_, _tmp3_);
		i = _tmp4_;
		_tmp5_ = self->priv->_keys;
		_tmp6_ = i;
		my_ilist_remove_at ((MyIList*) _tmp5_, _tmp6_);
		_tmp7_ = self->priv->_values;
		_tmp8_ = i;
		_tmp9_ = my_ilist_get ((MyIList*) _tmp7_, _tmp8_);
		((_vala_val == NULL) || (self->priv->v_destroy_func == NULL)) ? NULL : (_vala_val = (self->priv->v_destroy_func (_vala_val), NULL));
		_vala_val = _tmp9_;
		_tmp10_ = self->priv->_values;
		_tmp11_ = i;
		my_ilist_remove_at ((MyIList*) _tmp10_, _tmp11_);
		result = TRUE;
		if (val) {
			*val = _vala_val;
		} else {
			((_vala_val == NULL) || (self->priv->v_destroy_func == NULL)) ? NULL : (_vala_val = (self->priv->v_destroy_func (_vala_val), NULL));
		}
		return result;
	}
	result = FALSE;
	if (val) {
		*val = _vala_val;
	} else {
		((_vala_val == NULL) || (self->priv->v_destroy_func == NULL)) ? NULL : (_vala_val = (self->priv->v_destroy_func (_vala_val), NULL));
	}
	return result;
}


static gboolean my_dictionary_real_has_key (MyIDictionary* base, gconstpointer key) {
	MyDictionary * self;
	gboolean result = FALSE;
	MyList* _tmp0_;
	gconstpointer _tmp1_;
	gboolean _tmp2_ = FALSE;
	self = (MyDictionary*) base;
	_tmp0_ = self->priv->_keys;
	_tmp1_ = key;
	_tmp2_ = my_ilist_contains ((MyIList*) _tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


static gboolean my_dictionary_real_has_value (MyIDictionary* base, gconstpointer val) {
	MyDictionary * self;
	gboolean result = FALSE;
	MyList* _tmp0_;
	gconstpointer _tmp1_;
	gboolean _tmp2_ = FALSE;
	self = (MyDictionary*) base;
	_tmp0_ = self->priv->_values;
	_tmp1_ = val;
	_tmp2_ = my_ilist_contains ((MyIList*) _tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


GEqualFunc my_dictionary_get_keys_func (MyDictionary* self) {
	GEqualFunc result;
	GEqualFunc _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->kf;
	result = _tmp0_;
	return result;
}


GEqualFunc my_dictionary_get_values_func (MyDictionary* self) {
	GEqualFunc result;
	GEqualFunc _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->vf;
	result = _tmp0_;
	return result;
}


static MyIList* my_dictionary_real_get_keys (MyIDictionary* base) {
	MyIList* result;
	MyDictionary* self;
	MyList* _tmp0_;
	self = (MyDictionary*) base;
	_tmp0_ = self->priv->_keys;
	result = (MyIList*) _tmp0_;
	return result;
}


static MyIList* my_dictionary_real_get_values (MyIDictionary* base) {
	MyIList* result;
	MyDictionary* self;
	MyList* _tmp0_;
	self = (MyDictionary*) base;
	_tmp0_ = self->priv->_values;
	result = (MyIList*) _tmp0_;
	return result;
}


static gint my_dictionary_real_get_size (MyIDictionary* base) {
	gint result;
	MyDictionary* self;
	MyList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	self = (MyDictionary*) base;
	_tmp0_ = self->priv->_keys;
	_tmp1_ = my_ilist_get_size ((MyIList*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


MyIList* my_dictionary_get_entries (MyDictionary* self) {
	MyIList* result;
	MyList* _tmp0_;
	MyList* _tmp20_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = my_list_new (MY_TYPE_ENTRY, (GBoxedCopyFunc) my_entry_ref, my_entry_unref, NULL, NULL);
	_g_object_unref0 (self->priv->_entries);
	self->priv->_entries = _tmp0_;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_;
				gint _tmp4_;
				gint _tmp5_;
				gint _tmp6_;
				MyList* _tmp7_;
				MyIList* _tmp8_;
				MyIList* _tmp9_;
				gint _tmp10_;
				gpointer _tmp11_ = NULL;
				gpointer _tmp12_;
				MyIList* _tmp13_;
				MyIList* _tmp14_;
				gint _tmp15_;
				gpointer _tmp16_ = NULL;
				gpointer _tmp17_;
				MyEntry* _tmp18_;
				MyEntry* _tmp19_;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = my_idictionary_get_size ((MyIDictionary*) self);
				_tmp6_ = _tmp5_;
				if (!(_tmp4_ < _tmp6_)) {
					break;
				}
				_tmp7_ = self->priv->_entries;
				_tmp8_ = my_idictionary_get_keys ((MyIDictionary*) self);
				_tmp9_ = _tmp8_;
				_tmp10_ = i;
				_tmp11_ = my_ilist_get (_tmp9_, _tmp10_);
				_tmp12_ = _tmp11_;
				_tmp13_ = my_idictionary_get_values ((MyIDictionary*) self);
				_tmp14_ = _tmp13_;
				_tmp15_ = i;
				_tmp16_ = my_ilist_get (_tmp14_, _tmp15_);
				_tmp17_ = _tmp16_;
				_tmp18_ = my_entry_new (self->priv->k_type, (GBoxedCopyFunc) self->priv->k_dup_func, self->priv->k_destroy_func, self->priv->v_type, (GBoxedCopyFunc) self->priv->v_dup_func, self->priv->v_destroy_func, _tmp12_, _tmp17_);
				_tmp19_ = _tmp18_;
				my_ilist_add ((MyIList*) _tmp7_, _tmp19_);
				_my_entry_unref0 (_tmp19_);
				((_tmp17_ == NULL) || (self->priv->v_destroy_func == NULL)) ? NULL : (_tmp17_ = (self->priv->v_destroy_func (_tmp17_), NULL));
				((_tmp12_ == NULL) || (self->priv->k_destroy_func == NULL)) ? NULL : (_tmp12_ = (self->priv->k_destroy_func (_tmp12_), NULL));
			}
		}
	}
	_tmp20_ = self->priv->_entries;
	result = (MyIList*) _tmp20_;
	return result;
}


static void my_dictionary_class_init (MyDictionaryClass * klass) {
	my_dictionary_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MyDictionaryPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_my_dictionary_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_my_dictionary_set_property;
	G_OBJECT_CLASS (klass)->finalize = my_dictionary_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_K_TYPE, g_param_spec_gtype ("k-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_K_DUP_FUNC, g_param_spec_pointer ("k-dup-func", "dup func", "dup func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_K_DESTROY_FUNC, g_param_spec_pointer ("k-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_V_TYPE, g_param_spec_gtype ("v-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_V_DUP_FUNC, g_param_spec_pointer ("v-dup-func", "dup func", "dup func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_V_DESTROY_FUNC, g_param_spec_pointer ("v-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_KEYS_FUNC, g_param_spec_pointer ("keys-func", "keys-func", "keys-func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_VALUES_FUNC, g_param_spec_pointer ("values-func", "values-func", "values-func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_KEYS, g_param_spec_object ("keys", "keys", "keys", MY_TYPE_ILIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_VALUES, g_param_spec_object ("values", "values", "values", MY_TYPE_ILIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_SIZE, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_DICTIONARY_ENTRIES, g_param_spec_object ("entries", "entries", "entries", MY_TYPE_ILIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void my_dictionary_my_idictionary_interface_init (MyIDictionaryIface * iface) {
	my_dictionary_my_idictionary_parent_iface = g_type_interface_peek_parent (iface);
	iface->add = (void (*)(MyIDictionary*, gconstpointer, gconstpointer)) my_dictionary_real_add;
	iface->get = (gpointer (*)(MyIDictionary*, gconstpointer)) my_dictionary_real_get;
	iface->set = (void (*)(MyIDictionary*, gconstpointer, gconstpointer)) my_dictionary_real_set;
	iface->unset = (gboolean (*)(MyIDictionary*, gconstpointer, gpointer*)) my_dictionary_real_unset;
	iface->has_key = (gboolean (*)(MyIDictionary*, gconstpointer)) my_dictionary_real_has_key;
	iface->has_value = (gboolean (*)(MyIDictionary*, gconstpointer)) my_dictionary_real_has_value;
	iface->get_keys = my_dictionary_real_get_keys;
	iface->get_values = my_dictionary_real_get_values;
	iface->get_size = my_dictionary_real_get_size;
}


static void my_dictionary_instance_init (MyDictionary * self) {
	self->priv = MY_DICTIONARY_GET_PRIVATE (self);
}


static void my_dictionary_finalize (GObject* obj) {
	MyDictionary * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MY_TYPE_DICTIONARY, MyDictionary);
	_g_object_unref0 (self->priv->_keys);
	_g_object_unref0 (self->priv->_values);
	_g_object_unref0 (self->priv->_entries);
	G_OBJECT_CLASS (my_dictionary_parent_class)->finalize (obj);
}


GType my_dictionary_get_type (void) {
	static volatile gsize my_dictionary_type_id__volatile = 0;
	if (g_once_init_enter (&my_dictionary_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyDictionaryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_dictionary_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyDictionary), 0, (GInstanceInitFunc) my_dictionary_instance_init, NULL };
		static const GInterfaceInfo my_idictionary_info = { (GInterfaceInitFunc) my_dictionary_my_idictionary_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType my_dictionary_type_id;
		my_dictionary_type_id = g_type_register_static (G_TYPE_OBJECT, "MyDictionary", &g_define_type_info, 0);
		g_type_add_interface_static (my_dictionary_type_id, MY_TYPE_IDICTIONARY, &my_idictionary_info);
		g_once_init_leave (&my_dictionary_type_id__volatile, my_dictionary_type_id);
	}
	return my_dictionary_type_id__volatile;
}


static void _vala_my_dictionary_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MyDictionary * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MY_TYPE_DICTIONARY, MyDictionary);
	switch (property_id) {
		case MY_DICTIONARY_KEYS_FUNC:
		g_value_set_pointer (value, my_dictionary_get_keys_func (self));
		break;
		case MY_DICTIONARY_VALUES_FUNC:
		g_value_set_pointer (value, my_dictionary_get_values_func (self));
		break;
		case MY_DICTIONARY_KEYS:
		g_value_set_object (value, my_idictionary_get_keys ((MyIDictionary*) self));
		break;
		case MY_DICTIONARY_VALUES:
		g_value_set_object (value, my_idictionary_get_values ((MyIDictionary*) self));
		break;
		case MY_DICTIONARY_SIZE:
		g_value_set_int (value, my_idictionary_get_size ((MyIDictionary*) self));
		break;
		case MY_DICTIONARY_ENTRIES:
		g_value_set_object (value, my_dictionary_get_entries (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_my_dictionary_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MyDictionary * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MY_TYPE_DICTIONARY, MyDictionary);
	switch (property_id) {
		case MY_DICTIONARY_K_TYPE:
		self->priv->k_type = g_value_get_gtype (value);
		break;
		case MY_DICTIONARY_K_DUP_FUNC:
		self->priv->k_dup_func = g_value_get_pointer (value);
		break;
		case MY_DICTIONARY_K_DESTROY_FUNC:
		self->priv->k_destroy_func = g_value_get_pointer (value);
		break;
		case MY_DICTIONARY_V_TYPE:
		self->priv->v_type = g_value_get_gtype (value);
		break;
		case MY_DICTIONARY_V_DUP_FUNC:
		self->priv->v_dup_func = g_value_get_pointer (value);
		break;
		case MY_DICTIONARY_V_DESTROY_FUNC:
		self->priv->v_destroy_func = g_value_get_pointer (value);
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



