/* my.entry.c generated by valac 0.20.0, the Vala compiler
 * generated from my.entry.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define MY_TYPE_ENTRY (my_entry_get_type ())
#define MY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ENTRY, MyEntry))
#define MY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_TYPE_ENTRY, MyEntryClass))
#define MY_IS_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ENTRY))
#define MY_IS_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_TYPE_ENTRY))
#define MY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_TYPE_ENTRY, MyEntryClass))

typedef struct _MyEntry MyEntry;
typedef struct _MyEntryClass MyEntryClass;
typedef struct _MyEntryPrivate MyEntryPrivate;
#define _k_destroy_func0(var) (((var == NULL) || (k_destroy_func == NULL)) ? NULL : (var = (k_destroy_func (var), NULL)))
#define _v_destroy_func0(var) (((var == NULL) || (v_destroy_func == NULL)) ? NULL : (var = (v_destroy_func (var), NULL)))
typedef struct _MyParamSpecEntry MyParamSpecEntry;

struct _MyEntry {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MyEntryPrivate * priv;
};

struct _MyEntryClass {
	GTypeClass parent_class;
	void (*finalize) (MyEntry *self);
};

struct _MyEntryPrivate {
	GType k_type;
	GBoxedCopyFunc k_dup_func;
	GDestroyNotify k_destroy_func;
	GType v_type;
	GBoxedCopyFunc v_dup_func;
	GDestroyNotify v_destroy_func;
	gpointer _key;
	gpointer _value;
};

struct _MyParamSpecEntry {
	GParamSpec parent_instance;
};


static gpointer my_entry_parent_class = NULL;

gpointer my_entry_ref (gpointer instance);
void my_entry_unref (gpointer instance);
GParamSpec* my_param_spec_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void my_value_set_entry (GValue* value, gpointer v_object);
void my_value_take_entry (GValue* value, gpointer v_object);
gpointer my_value_get_entry (const GValue* value);
GType my_entry_get_type (void) G_GNUC_CONST;
#define MY_ENTRY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MY_TYPE_ENTRY, MyEntryPrivate))
enum  {
	MY_ENTRY_DUMMY_PROPERTY
};
MyEntry* my_entry_new (GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, gconstpointer k, gconstpointer v);
MyEntry* my_entry_construct (GType object_type, GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, gconstpointer k, gconstpointer v);
gconstpointer my_entry_get_key (MyEntry* self);
void my_entry_set_key (MyEntry* self, gconstpointer value);
gconstpointer my_entry_get_value (MyEntry* self);
void my_entry_set_value (MyEntry* self, gconstpointer value);
static void my_entry_finalize (MyEntry* obj);


MyEntry* my_entry_construct (GType object_type, GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, gconstpointer k, gconstpointer v) {
	MyEntry* self = NULL;
	gconstpointer _tmp0_;
	gpointer _tmp1_;
	gconstpointer _tmp2_;
	gpointer _tmp3_;
	self = (MyEntry*) g_type_create_instance (object_type);
	self->priv->k_type = k_type;
	self->priv->k_dup_func = k_dup_func;
	self->priv->k_destroy_func = k_destroy_func;
	self->priv->v_type = v_type;
	self->priv->v_dup_func = v_dup_func;
	self->priv->v_destroy_func = v_destroy_func;
	_tmp0_ = k;
	_tmp1_ = ((_tmp0_ != NULL) && (k_dup_func != NULL)) ? k_dup_func ((gpointer) _tmp0_) : ((gpointer) _tmp0_);
	_k_destroy_func0 (self->priv->_key);
	self->priv->_key = _tmp1_;
	_tmp2_ = v;
	_tmp3_ = ((_tmp2_ != NULL) && (v_dup_func != NULL)) ? v_dup_func ((gpointer) _tmp2_) : ((gpointer) _tmp2_);
	_v_destroy_func0 (self->priv->_value);
	self->priv->_value = _tmp3_;
	return self;
}


MyEntry* my_entry_new (GType k_type, GBoxedCopyFunc k_dup_func, GDestroyNotify k_destroy_func, GType v_type, GBoxedCopyFunc v_dup_func, GDestroyNotify v_destroy_func, gconstpointer k, gconstpointer v) {
	return my_entry_construct (MY_TYPE_ENTRY, k_type, k_dup_func, k_destroy_func, v_type, v_dup_func, v_destroy_func, k, v);
}


gconstpointer my_entry_get_key (MyEntry* self) {
	gconstpointer result;
	gconstpointer _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_key;
	result = _tmp0_;
	return result;
}


void my_entry_set_key (MyEntry* self, gconstpointer value) {
	gconstpointer _tmp0_;
	gpointer _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = ((_tmp0_ != NULL) && (self->priv->k_dup_func != NULL)) ? self->priv->k_dup_func ((gpointer) _tmp0_) : ((gpointer) _tmp0_);
	((self->priv->_key == NULL) || (self->priv->k_destroy_func == NULL)) ? NULL : (self->priv->_key = (self->priv->k_destroy_func (self->priv->_key), NULL));
	self->priv->_key = _tmp1_;
}


gconstpointer my_entry_get_value (MyEntry* self) {
	gconstpointer result;
	gconstpointer _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_value;
	result = _tmp0_;
	return result;
}


void my_entry_set_value (MyEntry* self, gconstpointer value) {
	gconstpointer _tmp0_;
	gpointer _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = ((_tmp0_ != NULL) && (self->priv->v_dup_func != NULL)) ? self->priv->v_dup_func ((gpointer) _tmp0_) : ((gpointer) _tmp0_);
	((self->priv->_value == NULL) || (self->priv->v_destroy_func == NULL)) ? NULL : (self->priv->_value = (self->priv->v_destroy_func (self->priv->_value), NULL));
	self->priv->_value = _tmp1_;
}


static void my_value_entry_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void my_value_entry_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		my_entry_unref (value->data[0].v_pointer);
	}
}


static void my_value_entry_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = my_entry_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer my_value_entry_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* my_value_entry_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		MyEntry* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = my_entry_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* my_value_entry_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	MyEntry** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = my_entry_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* my_param_spec_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	MyParamSpecEntry* spec;
	g_return_val_if_fail (g_type_is_a (object_type, MY_TYPE_ENTRY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer my_value_get_entry (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MY_TYPE_ENTRY), NULL);
	return value->data[0].v_pointer;
}


void my_value_set_entry (GValue* value, gpointer v_object) {
	MyEntry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MY_TYPE_ENTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, MY_TYPE_ENTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		my_entry_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		my_entry_unref (old);
	}
}


void my_value_take_entry (GValue* value, gpointer v_object) {
	MyEntry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MY_TYPE_ENTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, MY_TYPE_ENTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		my_entry_unref (old);
	}
}


static void my_entry_class_init (MyEntryClass * klass) {
	my_entry_parent_class = g_type_class_peek_parent (klass);
	MY_ENTRY_CLASS (klass)->finalize = my_entry_finalize;
	g_type_class_add_private (klass, sizeof (MyEntryPrivate));
}


static void my_entry_instance_init (MyEntry * self) {
	self->priv = MY_ENTRY_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void my_entry_finalize (MyEntry* obj) {
	MyEntry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MY_TYPE_ENTRY, MyEntry);
	((self->priv->_key == NULL) || (self->priv->k_destroy_func == NULL)) ? NULL : (self->priv->_key = (self->priv->k_destroy_func (self->priv->_key), NULL));
	((self->priv->_value == NULL) || (self->priv->v_destroy_func == NULL)) ? NULL : (self->priv->_value = (self->priv->v_destroy_func (self->priv->_value), NULL));
}


GType my_entry_get_type (void) {
	static volatile gsize my_entry_type_id__volatile = 0;
	if (g_once_init_enter (&my_entry_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { my_value_entry_init, my_value_entry_free_value, my_value_entry_copy_value, my_value_entry_peek_pointer, "p", my_value_entry_collect_value, "p", my_value_entry_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (MyEntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyEntry), 0, (GInstanceInitFunc) my_entry_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType my_entry_type_id;
		my_entry_type_id = g_type_register_fundamental (g_type_fundamental_next (), "MyEntry", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&my_entry_type_id__volatile, my_entry_type_id);
	}
	return my_entry_type_id__volatile;
}


gpointer my_entry_ref (gpointer instance) {
	MyEntry* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void my_entry_unref (gpointer instance) {
	MyEntry* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		MY_ENTRY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



