/* my.functions.c generated by valac 0.20.0, the Vala compiler
 * generated from my.functions.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




GEqualFunc my_functions_equal_func_for (GType t);
GCompareFunc my_functions_compare_func_for (GType t);
gint my_functions_direct_compare (void* _val1, void* _val2);
static gint _my_functions_direct_compare_gcompare_func (gconstpointer a, gconstpointer b);


GEqualFunc my_functions_equal_func_for (GType t) {
	GEqualFunc result = NULL;
	GType _tmp0_;
	GEqualFunc _tmp2_;
	_tmp0_ = t;
	if (_tmp0_ == G_TYPE_STRING) {
		GEqualFunc _tmp1_;
		_tmp1_ = g_str_equal;
		result = _tmp1_;
		return result;
	}
	_tmp2_ = g_direct_equal;
	result = _tmp2_;
	return result;
}


static gint _my_functions_direct_compare_gcompare_func (gconstpointer a, gconstpointer b) {
	gint result;
	result = my_functions_direct_compare (a, b);
	return result;
}


GCompareFunc my_functions_compare_func_for (GType t) {
	GCompareFunc result = NULL;
	GType _tmp0_;
	_tmp0_ = t;
	if (_tmp0_ == G_TYPE_STRING) {
		GCompareFunc _tmp1_;
		_tmp1_ = g_strcmp0;
		result = (GCompareFunc) _tmp1_;
		return result;
	}
	result = _my_functions_direct_compare_gcompare_func;
	return result;
}


gint my_functions_direct_compare (void* _val1, void* _val2) {
	gint result = 0;
	void* _tmp0_;
	glong val1;
	void* _tmp1_;
	glong val2;
	glong _tmp2_;
	glong _tmp3_;
	_tmp0_ = _val1;
	val1 = (glong) _tmp0_;
	_tmp1_ = _val2;
	val2 = (glong) _tmp1_;
	_tmp2_ = val1;
	_tmp3_ = val2;
	if (_tmp2_ > _tmp3_) {
		result = 1;
		return result;
	} else {
		glong _tmp4_;
		glong _tmp5_;
		_tmp4_ = val1;
		_tmp5_ = val2;
		if (_tmp4_ == _tmp5_) {
			result = 0;
			return result;
		} else {
			result = -1;
			return result;
		}
	}
}



