/* my.iequatable.c generated by valac 0.20.0, the Vala compiler
 * generated from my.iequatable.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define MY_TYPE_IEQUATABLE (my_iequatable_get_type ())
#define MY_IEQUATABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_IEQUATABLE, MyIEquatable))
#define MY_IS_IEQUATABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_IEQUATABLE))
#define MY_IEQUATABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_IEQUATABLE, MyIEquatableIface))

typedef struct _MyIEquatable MyIEquatable;
typedef struct _MyIEquatableIface MyIEquatableIface;

struct _MyIEquatableIface {
	GTypeInterface parent_iface;
	gboolean (*equals) (MyIEquatable* self, GObject* other);
};



GType my_iequatable_get_type (void) G_GNUC_CONST;
gboolean my_iequatable_equals (MyIEquatable* self, GObject* other);


gboolean my_iequatable_equals (MyIEquatable* self, GObject* other) {
	g_return_val_if_fail (self != NULL, FALSE);
	return MY_IEQUATABLE_GET_INTERFACE (self)->equals (self, other);
}


static void my_iequatable_base_init (MyIEquatableIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType my_iequatable_get_type (void) {
	static volatile gsize my_iequatable_type_id__volatile = 0;
	if (g_once_init_enter (&my_iequatable_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyIEquatableIface), (GBaseInitFunc) my_iequatable_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType my_iequatable_type_id;
		my_iequatable_type_id = g_type_register_static (G_TYPE_INTERFACE, "MyIEquatable", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (my_iequatable_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&my_iequatable_type_id__volatile, my_iequatable_type_id);
	}
	return my_iequatable_type_id__volatile;
}



