/* my.idictionary.c generated by valac 0.20.0, the Vala compiler
 * generated from my.idictionary.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define MY_TYPE_IDICTIONARY (my_idictionary_get_type ())
#define MY_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_IDICTIONARY, MyIDictionary))
#define MY_IS_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_IDICTIONARY))
#define MY_IDICTIONARY_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_IDICTIONARY, MyIDictionaryIface))

typedef struct _MyIDictionary MyIDictionary;
typedef struct _MyIDictionaryIface MyIDictionaryIface;

#define MY_TYPE_ILIST (my_ilist_get_type ())
#define MY_ILIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ILIST, MyIList))
#define MY_IS_ILIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ILIST))
#define MY_ILIST_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_ILIST, MyIListIface))

typedef struct _MyIList MyIList;
typedef struct _MyIListIface MyIListIface;

struct _MyIListIface {
	GTypeInterface parent_iface;
	gpointer (*get) (MyIList* self, gint index);
	void (*set) (MyIList* self, gint index, gconstpointer val);
	void (*add) (MyIList* self, gconstpointer item);
	void (*add_range) (MyIList* self, gpointer* items, int items_length1);
	void (*add_collection) (MyIList* self, MyIList* coll);
	gboolean (*contains) (MyIList* self, gconstpointer item);
	void (*insert) (MyIList* self, gint position, gconstpointer item);
	void (*insert_all) (MyIList* self, gint position, gpointer* items, int items_length1);
	void (*insert_collection) (MyIList* self, gint position, MyIList* coll);
	void (*reverse) (MyIList* self);
	gint (*index_of) (MyIList* self, gconstpointer item);
	gint* (*index_of_all) (MyIList* self, gconstpointer item, int* result_length1);
	void (*remove) (MyIList* self, gconstpointer item);
	void (*remove_at) (MyIList* self, gint index);
	void (*remove_all) (MyIList* self, gconstpointer item);
	void (*remove_range) (MyIList* self, gint start, gint length);
	gint (*get_size) (MyIList* self);
};

struct _MyIDictionaryIface {
	GTypeInterface parent_iface;
	void (*add) (MyIDictionary* self, gconstpointer key, gconstpointer val);
	gpointer (*get) (MyIDictionary* self, gconstpointer key);
	void (*set) (MyIDictionary* self, gconstpointer key, gconstpointer val);
	gboolean (*unset) (MyIDictionary* self, gconstpointer key, gpointer* val);
	gboolean (*has_key) (MyIDictionary* self, gconstpointer key);
	gboolean (*has_value) (MyIDictionary* self, gconstpointer val);
	MyIList* (*get_keys) (MyIDictionary* self);
	MyIList* (*get_values) (MyIDictionary* self);
	gint (*get_size) (MyIDictionary* self);
};



GType my_ilist_get_type (void) G_GNUC_CONST;
GType my_idictionary_get_type (void) G_GNUC_CONST;
void my_idictionary_add (MyIDictionary* self, gconstpointer key, gconstpointer val);
gpointer my_idictionary_get (MyIDictionary* self, gconstpointer key);
void my_idictionary_set (MyIDictionary* self, gconstpointer key, gconstpointer val);
gboolean my_idictionary_unset (MyIDictionary* self, gconstpointer key, gpointer* val);
gboolean my_idictionary_has_key (MyIDictionary* self, gconstpointer key);
gboolean my_idictionary_has_value (MyIDictionary* self, gconstpointer val);
MyIList* my_idictionary_get_keys (MyIDictionary* self);
MyIList* my_idictionary_get_values (MyIDictionary* self);
gint my_idictionary_get_size (MyIDictionary* self);


void my_idictionary_add (MyIDictionary* self, gconstpointer key, gconstpointer val) {
	g_return_if_fail (self != NULL);
	MY_IDICTIONARY_GET_INTERFACE (self)->add (self, key, val);
}


gpointer my_idictionary_get (MyIDictionary* self, gconstpointer key) {
	g_return_val_if_fail (self != NULL, NULL);
	return MY_IDICTIONARY_GET_INTERFACE (self)->get (self, key);
}


void my_idictionary_set (MyIDictionary* self, gconstpointer key, gconstpointer val) {
	g_return_if_fail (self != NULL);
	MY_IDICTIONARY_GET_INTERFACE (self)->set (self, key, val);
}


gboolean my_idictionary_unset (MyIDictionary* self, gconstpointer key, gpointer* val) {
	g_return_val_if_fail (self != NULL, FALSE);
	return MY_IDICTIONARY_GET_INTERFACE (self)->unset (self, key, val);
}


gboolean my_idictionary_has_key (MyIDictionary* self, gconstpointer key) {
	g_return_val_if_fail (self != NULL, FALSE);
	return MY_IDICTIONARY_GET_INTERFACE (self)->has_key (self, key);
}


gboolean my_idictionary_has_value (MyIDictionary* self, gconstpointer val) {
	g_return_val_if_fail (self != NULL, FALSE);
	return MY_IDICTIONARY_GET_INTERFACE (self)->has_value (self, val);
}


MyIList* my_idictionary_get_keys (MyIDictionary* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return MY_IDICTIONARY_GET_INTERFACE (self)->get_keys (self);
}


MyIList* my_idictionary_get_values (MyIDictionary* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return MY_IDICTIONARY_GET_INTERFACE (self)->get_values (self);
}


gint my_idictionary_get_size (MyIDictionary* self) {
	g_return_val_if_fail (self != NULL, 0);
	return MY_IDICTIONARY_GET_INTERFACE (self)->get_size (self);
}


static void my_idictionary_base_init (MyIDictionaryIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_object_interface_install_property (iface, g_param_spec_object ("keys", "keys", "keys", MY_TYPE_ILIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
		g_object_interface_install_property (iface, g_param_spec_object ("values", "values", "values", MY_TYPE_ILIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
		g_object_interface_install_property (iface, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	}
}


GType my_idictionary_get_type (void) {
	static volatile gsize my_idictionary_type_id__volatile = 0;
	if (g_once_init_enter (&my_idictionary_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyIDictionaryIface), (GBaseInitFunc) my_idictionary_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType my_idictionary_type_id;
		my_idictionary_type_id = g_type_register_static (G_TYPE_INTERFACE, "MyIDictionary", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (my_idictionary_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&my_idictionary_type_id__volatile, my_idictionary_type_id);
	}
	return my_idictionary_type_id__volatile;
}



