/* my.ilist.c generated by valac 0.20.0, the Vala compiler
 * generated from my.ilist.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define MY_TYPE_ILIST (my_ilist_get_type ())
#define MY_ILIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ILIST, MyIList))
#define MY_IS_ILIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ILIST))
#define MY_ILIST_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_ILIST, MyIListIface))

typedef struct _MyIList MyIList;
typedef struct _MyIListIface MyIListIface;

struct _MyIListIface {
	GTypeInterface parent_iface;
	gpointer (*get) (MyIList* self, gint index);
	void (*set) (MyIList* self, gint index, gconstpointer val);
	void (*add) (MyIList* self, gconstpointer item);
	void (*add_range) (MyIList* self, gpointer* items, int items_length1);
	void (*add_collection) (MyIList* self, MyIList* coll);
	gboolean (*contains) (MyIList* self, gconstpointer item);
	void (*insert) (MyIList* self, gint position, gconstpointer item);
	void (*insert_all) (MyIList* self, gint position, gpointer* items, int items_length1);
	void (*insert_collection) (MyIList* self, gint position, MyIList* coll);
	void (*reverse) (MyIList* self);
	gint (*index_of) (MyIList* self, gconstpointer item);
	gint* (*index_of_all) (MyIList* self, gconstpointer item, int* result_length1);
	void (*remove) (MyIList* self, gconstpointer item);
	void (*remove_at) (MyIList* self, gint index);
	void (*remove_all) (MyIList* self, gconstpointer item);
	void (*remove_range) (MyIList* self, gint start, gint length);
	gint (*get_size) (MyIList* self);
};



GType my_ilist_get_type (void) G_GNUC_CONST;
gpointer my_ilist_get (MyIList* self, gint index);
void my_ilist_set (MyIList* self, gint index, gconstpointer val);
void my_ilist_add (MyIList* self, gconstpointer item);
void my_ilist_add_range (MyIList* self, gpointer* items, int items_length1);
void my_ilist_add_collection (MyIList* self, MyIList* coll);
gboolean my_ilist_contains (MyIList* self, gconstpointer item);
void my_ilist_insert (MyIList* self, gint position, gconstpointer item);
void my_ilist_insert_all (MyIList* self, gint position, gpointer* items, int items_length1);
void my_ilist_insert_collection (MyIList* self, gint position, MyIList* coll);
void my_ilist_reverse (MyIList* self);
gint my_ilist_index_of (MyIList* self, gconstpointer item);
gint* my_ilist_index_of_all (MyIList* self, gconstpointer item, int* result_length1);
void my_ilist_remove (MyIList* self, gconstpointer item);
void my_ilist_remove_at (MyIList* self, gint index);
void my_ilist_remove_all (MyIList* self, gconstpointer item);
void my_ilist_remove_range (MyIList* self, gint start, gint length);
gint my_ilist_get_size (MyIList* self);


gpointer my_ilist_get (MyIList* self, gint index) {
	g_return_val_if_fail (self != NULL, NULL);
	return MY_ILIST_GET_INTERFACE (self)->get (self, index);
}


void my_ilist_set (MyIList* self, gint index, gconstpointer val) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->set (self, index, val);
}


void my_ilist_add (MyIList* self, gconstpointer item) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->add (self, item);
}


void my_ilist_add_range (MyIList* self, gpointer* items, int items_length1) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->add_range (self, items, items_length1);
}


void my_ilist_add_collection (MyIList* self, MyIList* coll) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->add_collection (self, coll);
}


gboolean my_ilist_contains (MyIList* self, gconstpointer item) {
	g_return_val_if_fail (self != NULL, FALSE);
	return MY_ILIST_GET_INTERFACE (self)->contains (self, item);
}


void my_ilist_insert (MyIList* self, gint position, gconstpointer item) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->insert (self, position, item);
}


void my_ilist_insert_all (MyIList* self, gint position, gpointer* items, int items_length1) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->insert_all (self, position, items, items_length1);
}


void my_ilist_insert_collection (MyIList* self, gint position, MyIList* coll) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->insert_collection (self, position, coll);
}


void my_ilist_reverse (MyIList* self) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->reverse (self);
}


gint my_ilist_index_of (MyIList* self, gconstpointer item) {
	g_return_val_if_fail (self != NULL, 0);
	return MY_ILIST_GET_INTERFACE (self)->index_of (self, item);
}


gint* my_ilist_index_of_all (MyIList* self, gconstpointer item, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return MY_ILIST_GET_INTERFACE (self)->index_of_all (self, item, result_length1);
}


void my_ilist_remove (MyIList* self, gconstpointer item) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->remove (self, item);
}


void my_ilist_remove_at (MyIList* self, gint index) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->remove_at (self, index);
}


void my_ilist_remove_all (MyIList* self, gconstpointer item) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->remove_all (self, item);
}


void my_ilist_remove_range (MyIList* self, gint start, gint length) {
	g_return_if_fail (self != NULL);
	MY_ILIST_GET_INTERFACE (self)->remove_range (self, start, length);
}


gint my_ilist_get_size (MyIList* self) {
	g_return_val_if_fail (self != NULL, 0);
	return MY_ILIST_GET_INTERFACE (self)->get_size (self);
}


static void my_ilist_base_init (MyIListIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_object_interface_install_property (iface, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	}
}


GType my_ilist_get_type (void) {
	static volatile gsize my_ilist_type_id__volatile = 0;
	if (g_once_init_enter (&my_ilist_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyIListIface), (GBaseInitFunc) my_ilist_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType my_ilist_type_id;
		my_ilist_type_id = g_type_register_static (G_TYPE_INTERFACE, "MyIList", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (my_ilist_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&my_ilist_type_id__volatile, my_ilist_type_id);
	}
	return my_ilist_type_id__volatile;
}



