/* my.list.c generated by valac 0.20.0, the Vala compiler
 * generated from my.list.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define MY_TYPE_ILIST (my_ilist_get_type ())
#define MY_ILIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ILIST, MyIList))
#define MY_IS_ILIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ILIST))
#define MY_ILIST_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_ILIST, MyIListIface))

typedef struct _MyIList MyIList;
typedef struct _MyIListIface MyIListIface;

#define MY_TYPE_ITERABLE (my_iterable_get_type ())
#define MY_ITERABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ITERABLE, MyIterable))
#define MY_IS_ITERABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ITERABLE))
#define MY_ITERABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_ITERABLE, MyIterableIface))

typedef struct _MyIterable MyIterable;
typedef struct _MyIterableIface MyIterableIface;

#define MY_TYPE_ITERATOR (my_iterator_get_type ())
#define MY_ITERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_ITERATOR, MyIterator))
#define MY_ITERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_TYPE_ITERATOR, MyIteratorClass))
#define MY_IS_ITERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_ITERATOR))
#define MY_IS_ITERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_TYPE_ITERATOR))
#define MY_ITERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_TYPE_ITERATOR, MyIteratorClass))

typedef struct _MyIterator MyIterator;
typedef struct _MyIteratorClass MyIteratorClass;

#define MY_TYPE_IEQUATABLE (my_iequatable_get_type ())
#define MY_IEQUATABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_IEQUATABLE, MyIEquatable))
#define MY_IS_IEQUATABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_IEQUATABLE))
#define MY_IEQUATABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MY_TYPE_IEQUATABLE, MyIEquatableIface))

typedef struct _MyIEquatable MyIEquatable;
typedef struct _MyIEquatableIface MyIEquatableIface;

#define MY_TYPE_LIST (my_list_get_type ())
#define MY_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_TYPE_LIST, MyList))
#define MY_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_TYPE_LIST, MyListClass))
#define MY_IS_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_TYPE_LIST))
#define MY_IS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_TYPE_LIST))
#define MY_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_TYPE_LIST, MyListClass))

typedef struct _MyList MyList;
typedef struct _MyListClass MyListClass;
typedef struct _MyListPrivate MyListPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _MyIListIface {
	GTypeInterface parent_iface;
	gpointer (*get) (MyIList* self, gint index);
	void (*set) (MyIList* self, gint index, gconstpointer val);
	void (*add) (MyIList* self, gconstpointer item);
	void (*add_range) (MyIList* self, gpointer* items, int items_length1);
	void (*add_collection) (MyIList* self, MyIList* coll);
	gboolean (*contains) (MyIList* self, gconstpointer item);
	void (*insert) (MyIList* self, gint position, gconstpointer item);
	void (*insert_all) (MyIList* self, gint position, gpointer* items, int items_length1);
	void (*insert_collection) (MyIList* self, gint position, MyIList* coll);
	void (*reverse) (MyIList* self);
	gint (*index_of) (MyIList* self, gconstpointer item);
	gint* (*index_of_all) (MyIList* self, gconstpointer item, int* result_length1);
	void (*remove) (MyIList* self, gconstpointer item);
	void (*remove_at) (MyIList* self, gint index);
	void (*remove_all) (MyIList* self, gconstpointer item);
	void (*remove_range) (MyIList* self, gint start, gint length);
	gint (*get_size) (MyIList* self);
};

struct _MyIterableIface {
	GTypeInterface parent_iface;
	MyIterator* (*iterator) (MyIterable* self);
};

struct _MyIEquatableIface {
	GTypeInterface parent_iface;
	gboolean (*equals) (MyIEquatable* self, GObject* other);
};

struct _MyList {
	GObject parent_instance;
	MyListPrivate * priv;
};

struct _MyListClass {
	GObjectClass parent_class;
};

struct _MyListPrivate {
	GType g_type;
	GBoxedCopyFunc g_dup_func;
	GDestroyNotify g_destroy_func;
	gpointer* array;
	gint array_length1;
	gint _array_size_;
	GEqualFunc f;
	GCompareFunc cf;
};


static gpointer my_list_parent_class = NULL;
static MyIListIface* my_list_my_ilist_parent_iface = NULL;
static MyIterableIface* my_list_my_iterable_parent_iface = NULL;
static MyIEquatableIface* my_list_my_iequatable_parent_iface = NULL;

GType my_ilist_get_type (void) G_GNUC_CONST;
gpointer my_iterator_ref (gpointer instance);
void my_iterator_unref (gpointer instance);
GParamSpec* my_param_spec_iterator (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void my_value_set_iterator (GValue* value, gpointer v_object);
void my_value_take_iterator (GValue* value, gpointer v_object);
gpointer my_value_get_iterator (const GValue* value);
GType my_iterator_get_type (void) G_GNUC_CONST;
GType my_iterable_get_type (void) G_GNUC_CONST;
GType my_iequatable_get_type (void) G_GNUC_CONST;
GType my_list_get_type (void) G_GNUC_CONST;
#define MY_LIST_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MY_TYPE_LIST, MyListPrivate))
enum  {
	MY_LIST_DUMMY_PROPERTY,
	MY_LIST_G_TYPE,
	MY_LIST_G_DUP_FUNC,
	MY_LIST_G_DESTROY_FUNC,
	MY_LIST_EQUAL_FUNC,
	MY_LIST_SIZE
};
void my_list_clear (MyList* self);
MyList* my_list_new (GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, GEqualFunc func, GCompareFunc cfunc);
MyList* my_list_construct (GType object_type, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, GEqualFunc func, GCompareFunc cfunc);
GEqualFunc my_functions_equal_func_for (GType t);
GCompareFunc my_functions_compare_func_for (GType t);
static void my_list_real_add (MyIList* base, gconstpointer item);
static gpointer* _vala_array_dup1 (gpointer* self, int length, GBoxedCopyFunc g_dup_func);
static void my_list_real_reverse (MyIList* base);
gint my_ilist_get_size (MyIList* self);
void my_ilist_add (MyIList* self, gconstpointer item);
gpointer* my_list_to_array (MyList* self, int* result_length1);
static void my_list_real_insert (MyIList* base, gint position, gconstpointer item);
static void my_list_real_insert_all (MyIList* base, gint position, gpointer* items, int items_length1);
void my_ilist_insert (MyIList* self, gint position, gconstpointer item);
static void my_list_real_insert_collection (MyIList* base, gint position, MyIList* collection);
gpointer my_ilist_get (MyIList* self, gint index);
MyList* my_list_slice (MyList* self, gint start, gint end);
void my_list_sort (MyList* self);
static void my_list_real_add_range (MyIList* base, gpointer* items, int items_length1);
static void my_list_real_add_collection (MyIList* base, MyIList* coll);
static gpointer my_list_real_get (MyIList* base, gint index);
static void my_list_real_set (MyIList* base, gint index, gconstpointer val);
static gboolean my_list_real_contains (MyIList* base, gconstpointer item);
gint my_ilist_index_of (MyIList* self, gconstpointer item);
static gint my_list_real_index_of (MyIList* base, gconstpointer item);
static gint* my_list_real_index_of_all (MyIList* base, gconstpointer item, int* result_length1);
static void my_list_real_remove_at (MyIList* base, gint index);
static void my_list_real_remove_range (MyIList* base, gint start, gint length);
void my_ilist_remove_at (MyIList* self, gint index);
static void my_list_real_remove_all (MyIList* base, gconstpointer item);
static void my_list_real_remove (MyIList* base, gconstpointer item);
static gpointer* _vala_array_dup2 (gpointer* self, int length, GBoxedCopyFunc g_dup_func);
static MyIterator* my_list_real_iterator (MyIterable* base);
MyIterator* my_iterator_new (GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, MyIList* i);
MyIterator* my_iterator_construct (GType object_type, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, MyIList* i);
static gboolean my_list_real_equals (MyIEquatable* base, GObject* o);
GEqualFunc my_list_get_equal_func (MyList* self);
static void my_list_finalize (GObject* obj);
static void _vala_my_list_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_my_list_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


MyList* my_list_construct (GType object_type, GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, GEqualFunc func, GCompareFunc cfunc) {
	MyList * self = NULL;
	GEqualFunc _tmp0_;
	GCompareFunc _tmp1_;
	GEqualFunc _tmp2_;
	GCompareFunc _tmp4_;
	gpointer* _tmp6_ = NULL;
	self = (MyList*) g_object_new (object_type, NULL);
	self->priv->g_type = g_type;
	self->priv->g_dup_func = g_dup_func;
	self->priv->g_destroy_func = g_destroy_func;
	_tmp0_ = func;
	self->priv->f = _tmp0_;
	_tmp1_ = cfunc;
	self->priv->cf = _tmp1_;
	_tmp2_ = func;
	if (_tmp2_ == NULL) {
		GEqualFunc _tmp3_ = NULL;
		_tmp3_ = my_functions_equal_func_for (g_type);
		self->priv->f = _tmp3_;
	}
	_tmp4_ = cfunc;
	if (_tmp4_ == NULL) {
		GCompareFunc _tmp5_ = NULL;
		_tmp5_ = my_functions_compare_func_for (g_type);
		self->priv->cf = _tmp5_;
	}
	_tmp6_ = g_new0 (gpointer, 0);
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) g_destroy_func), NULL);
	self->priv->array = _tmp6_;
	self->priv->array_length1 = 0;
	self->priv->_array_size_ = self->priv->array_length1;
	return self;
}


MyList* my_list_new (GType g_type, GBoxedCopyFunc g_dup_func, GDestroyNotify g_destroy_func, GEqualFunc func, GCompareFunc cfunc) {
	return my_list_construct (MY_TYPE_LIST, g_type, g_dup_func, g_destroy_func, func, cfunc);
}


static gpointer* _vala_array_dup1 (gpointer* self, int length, GBoxedCopyFunc g_dup_func) {
	gpointer* result;
	int i;
	result = g_new0 (gpointer, length);
	for (i = 0; i < length; i++) {
		gpointer _tmp0_;
		_tmp0_ = ((self[i] != NULL) && (g_dup_func != NULL)) ? g_dup_func ((gpointer) self[i]) : ((gpointer) self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static void my_list_real_add (MyIList* base, gconstpointer item) {
	MyList * self;
	gpointer* _tmp0_;
	gint _tmp0__length1;
	gpointer* _tmp1_ = NULL;
	gpointer* new_array;
	gint new_array_length1;
	gint _new_array_size_;
	gpointer* _tmp14_;
	gint _tmp14__length1;
	gpointer* _tmp15_;
	gint _tmp15__length1;
	gconstpointer _tmp16_;
	gpointer _tmp17_;
	gpointer _tmp18_;
	gpointer* _tmp19_;
	gint _tmp19__length1;
	gpointer* _tmp20_;
	gint _tmp20__length1;
	self = (MyList*) base;
	_tmp0_ = self->priv->array;
	_tmp0__length1 = self->priv->array_length1;
	_tmp1_ = g_new0 (gpointer, _tmp0__length1 + 1);
	new_array = _tmp1_;
	new_array_length1 = _tmp0__length1 + 1;
	_new_array_size_ = new_array_length1;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp2_;
			_tmp2_ = TRUE;
			while (TRUE) {
				gboolean _tmp3_;
				gint _tmp5_;
				gpointer* _tmp6_;
				gint _tmp6__length1;
				gpointer* _tmp7_;
				gint _tmp7__length1;
				gint _tmp8_;
				gpointer* _tmp9_;
				gint _tmp9__length1;
				gint _tmp10_;
				gconstpointer _tmp11_;
				gpointer _tmp12_;
				gpointer _tmp13_;
				_tmp3_ = _tmp2_;
				if (!_tmp3_) {
					gint _tmp4_;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp5_ = i;
				_tmp6_ = self->priv->array;
				_tmp6__length1 = self->priv->array_length1;
				if (!(_tmp5_ < _tmp6__length1)) {
					break;
				}
				_tmp7_ = new_array;
				_tmp7__length1 = new_array_length1;
				_tmp8_ = i;
				_tmp9_ = self->priv->array;
				_tmp9__length1 = self->priv->array_length1;
				_tmp10_ = i;
				_tmp11_ = _tmp9_[_tmp10_];
				_tmp12_ = ((_tmp11_ != NULL) && (self->priv->g_dup_func != NULL)) ? self->priv->g_dup_func ((gpointer) _tmp11_) : ((gpointer) _tmp11_);
				((_tmp7_[_tmp8_] == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (_tmp7_[_tmp8_] = (self->priv->g_destroy_func (_tmp7_[_tmp8_]), NULL));
				_tmp7_[_tmp8_] = _tmp12_;
				_tmp13_ = _tmp7_[_tmp8_];
			}
		}
	}
	_tmp14_ = new_array;
	_tmp14__length1 = new_array_length1;
	_tmp15_ = self->priv->array;
	_tmp15__length1 = self->priv->array_length1;
	_tmp16_ = item;
	_tmp17_ = ((_tmp16_ != NULL) && (self->priv->g_dup_func != NULL)) ? self->priv->g_dup_func ((gpointer) _tmp16_) : ((gpointer) _tmp16_);
	((_tmp14_[_tmp15__length1] == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (_tmp14_[_tmp15__length1] = (self->priv->g_destroy_func (_tmp14_[_tmp15__length1]), NULL));
	_tmp14_[_tmp15__length1] = _tmp17_;
	_tmp18_ = _tmp14_[_tmp15__length1];
	_tmp19_ = new_array;
	_tmp19__length1 = new_array_length1;
	_tmp20_ = (_tmp19_ != NULL) ? _vala_array_dup1 (_tmp19_, _tmp19__length1, self->priv->g_dup_func) : ((gpointer) _tmp19_);
	_tmp20__length1 = _tmp19__length1;
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
	self->priv->array = _tmp20_;
	self->priv->array_length1 = _tmp20__length1;
	self->priv->_array_size_ = self->priv->array_length1;
	new_array = (_vala_array_free (new_array, new_array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
}


static void my_list_real_reverse (MyIList* base) {
	MyList * self;
	MyList* _tmp0_;
	MyList* list;
	MyList* _tmp11_;
	gint _tmp12_ = 0;
	gpointer* _tmp13_ = NULL;
	self = (MyList*) base;
	_tmp0_ = my_list_new (self->priv->g_type, (GBoxedCopyFunc) self->priv->g_dup_func, self->priv->g_destroy_func, NULL, NULL);
	list = _tmp0_;
	{
		gint _tmp1_;
		gint _tmp2_;
		gint i;
		_tmp1_ = my_ilist_get_size ((MyIList*) self);
		_tmp2_ = _tmp1_;
		i = _tmp2_ - 1;
		{
			gboolean _tmp3_;
			_tmp3_ = TRUE;
			while (TRUE) {
				gboolean _tmp4_;
				gint _tmp6_;
				MyList* _tmp7_;
				gpointer* _tmp8_;
				gint _tmp8__length1;
				gint _tmp9_;
				gconstpointer _tmp10_;
				_tmp4_ = _tmp3_;
				if (!_tmp4_) {
					gint _tmp5_;
					_tmp5_ = i;
					i = _tmp5_ - 1;
				}
				_tmp3_ = FALSE;
				_tmp6_ = i;
				if (!(_tmp6_ > (-1))) {
					break;
				}
				_tmp7_ = list;
				_tmp8_ = self->priv->array;
				_tmp8__length1 = self->priv->array_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_];
				my_ilist_add ((MyIList*) _tmp7_, _tmp10_);
			}
		}
	}
	_tmp11_ = list;
	_tmp13_ = my_list_to_array (_tmp11_, &_tmp12_);
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
	self->priv->array = _tmp13_;
	self->priv->array_length1 = _tmp12_;
	self->priv->_array_size_ = self->priv->array_length1;
	_g_object_unref0 (list);
}


static void my_list_real_insert (MyIList* base, gint position, gconstpointer item) {
	MyList * self;
	MyList* _tmp0_;
	MyList* list;
	MyList* _tmp10_;
	gconstpointer _tmp11_;
	MyList* _tmp23_;
	gint _tmp24_ = 0;
	gpointer* _tmp25_ = NULL;
	self = (MyList*) base;
	_tmp0_ = my_list_new (self->priv->g_type, (GBoxedCopyFunc) self->priv->g_dup_func, self->priv->g_destroy_func, NULL, NULL);
	list = _tmp0_;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_;
				gint _tmp4_;
				gint _tmp5_;
				MyList* _tmp6_;
				gpointer* _tmp7_;
				gint _tmp7__length1;
				gint _tmp8_;
				gconstpointer _tmp9_;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = position;
				if (!(_tmp4_ < _tmp5_)) {
					break;
				}
				_tmp6_ = list;
				_tmp7_ = self->priv->array;
				_tmp7__length1 = self->priv->array_length1;
				_tmp8_ = i;
				_tmp9_ = _tmp7_[_tmp8_];
				my_ilist_add ((MyIList*) _tmp6_, _tmp9_);
			}
		}
	}
	_tmp10_ = list;
	_tmp11_ = item;
	my_ilist_add ((MyIList*) _tmp10_, _tmp11_);
	{
		gint _tmp12_;
		gint i;
		_tmp12_ = position;
		i = _tmp12_;
		{
			gboolean _tmp13_;
			_tmp13_ = TRUE;
			while (TRUE) {
				gboolean _tmp14_;
				gint _tmp16_;
				gint _tmp17_;
				gint _tmp18_;
				MyList* _tmp19_;
				gpointer* _tmp20_;
				gint _tmp20__length1;
				gint _tmp21_;
				gconstpointer _tmp22_;
				_tmp14_ = _tmp13_;
				if (!_tmp14_) {
					gint _tmp15_;
					_tmp15_ = i;
					i = _tmp15_ + 1;
				}
				_tmp13_ = FALSE;
				_tmp16_ = i;
				_tmp17_ = my_ilist_get_size ((MyIList*) self);
				_tmp18_ = _tmp17_;
				if (!(_tmp16_ < _tmp18_)) {
					break;
				}
				_tmp19_ = list;
				_tmp20_ = self->priv->array;
				_tmp20__length1 = self->priv->array_length1;
				_tmp21_ = i;
				_tmp22_ = _tmp20_[_tmp21_];
				my_ilist_add ((MyIList*) _tmp19_, _tmp22_);
			}
		}
	}
	_tmp23_ = list;
	_tmp25_ = my_list_to_array (_tmp23_, &_tmp24_);
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
	self->priv->array = _tmp25_;
	self->priv->array_length1 = _tmp24_;
	self->priv->_array_size_ = self->priv->array_length1;
	_g_object_unref0 (list);
}


static void my_list_real_insert_all (MyIList* base, gint position, gpointer* items, int items_length1) {
	MyList * self;
	self = (MyList*) base;
	{
		gpointer* _tmp0_;
		gint _tmp0__length1;
		gint i;
		_tmp0_ = items;
		_tmp0__length1 = items_length1;
		i = _tmp0__length1 - 1;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_;
				gint _tmp4_;
				gint _tmp5_;
				gpointer* _tmp6_;
				gint _tmp6__length1;
				gint _tmp7_;
				gconstpointer _tmp8_;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ - 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = i;
				if (!(_tmp4_ > (-1))) {
					break;
				}
				_tmp5_ = position;
				_tmp6_ = items;
				_tmp6__length1 = items_length1;
				_tmp7_ = i;
				_tmp8_ = _tmp6_[_tmp7_];
				my_ilist_insert ((MyIList*) self, _tmp5_, _tmp8_);
			}
		}
	}
}


static void my_list_real_insert_collection (MyIList* base, gint position, MyIList* collection) {
	MyList * self;
	self = (MyList*) base;
	g_return_if_fail (collection != NULL);
	{
		MyIList* _tmp0_;
		gint _tmp1_;
		gint _tmp2_;
		gint i;
		_tmp0_ = collection;
		_tmp1_ = my_ilist_get_size (_tmp0_);
		_tmp2_ = _tmp1_;
		i = _tmp2_ - 1;
		{
			gboolean _tmp3_;
			_tmp3_ = TRUE;
			while (TRUE) {
				gboolean _tmp4_;
				gint _tmp6_;
				gint _tmp7_;
				MyIList* _tmp8_;
				gint _tmp9_;
				gpointer _tmp10_ = NULL;
				gpointer _tmp11_;
				_tmp4_ = _tmp3_;
				if (!_tmp4_) {
					gint _tmp5_;
					_tmp5_ = i;
					i = _tmp5_ - 1;
				}
				_tmp3_ = FALSE;
				_tmp6_ = i;
				if (!(_tmp6_ > (-1))) {
					break;
				}
				_tmp7_ = position;
				_tmp8_ = collection;
				_tmp9_ = i;
				_tmp10_ = my_ilist_get (_tmp8_, _tmp9_);
				_tmp11_ = _tmp10_;
				my_ilist_insert ((MyIList*) self, _tmp7_, _tmp11_);
				((_tmp11_ == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (_tmp11_ = (self->priv->g_destroy_func (_tmp11_), NULL));
			}
		}
	}
}


MyList* my_list_slice (MyList* self, gint start, gint end) {
	MyList* result = NULL;
	MyList* _tmp0_;
	MyList* list;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = my_list_new (self->priv->g_type, (GBoxedCopyFunc) self->priv->g_dup_func, self->priv->g_destroy_func, NULL, NULL);
	list = _tmp0_;
	{
		gint _tmp1_;
		gint i;
		_tmp1_ = start;
		i = _tmp1_;
		{
			gboolean _tmp2_;
			_tmp2_ = TRUE;
			while (TRUE) {
				gboolean _tmp3_;
				gint _tmp5_;
				gint _tmp6_;
				MyList* _tmp7_;
				gpointer* _tmp8_;
				gint _tmp8__length1;
				gint _tmp9_;
				gconstpointer _tmp10_;
				_tmp3_ = _tmp2_;
				if (!_tmp3_) {
					gint _tmp4_;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp5_ = i;
				_tmp6_ = end;
				if (!(_tmp5_ <= _tmp6_)) {
					break;
				}
				_tmp7_ = list;
				_tmp8_ = self->priv->array;
				_tmp8__length1 = self->priv->array_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_];
				my_ilist_add ((MyIList*) _tmp7_, _tmp10_);
			}
		}
	}
	result = list;
	return result;
}


void my_list_sort (MyList* self) {
	MyList* _tmp0_;
	MyList* list;
	MyList* _tmp1_;
	gpointer* _tmp2_;
	gint _tmp2__length1;
	gconstpointer _tmp3_;
	gint c;
	MyList* _tmp41_;
	gint _tmp42_ = 0;
	gpointer* _tmp43_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = my_list_new (self->priv->g_type, (GBoxedCopyFunc) self->priv->g_dup_func, self->priv->g_destroy_func, NULL, NULL);
	list = _tmp0_;
	_tmp1_ = list;
	_tmp2_ = self->priv->array;
	_tmp2__length1 = self->priv->array_length1;
	_tmp3_ = _tmp2_[0];
	my_ilist_add ((MyIList*) _tmp1_, _tmp3_);
	c = 0;
	{
		gint i;
		i = 1;
		{
			gboolean _tmp4_;
			_tmp4_ = TRUE;
			while (TRUE) {
				gboolean _tmp5_;
				gint _tmp7_;
				gint _tmp8_;
				gint _tmp9_;
				gint _tmp36_;
				_tmp5_ = _tmp4_;
				if (!_tmp5_) {
					gint _tmp6_;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp7_ = i;
				_tmp8_ = my_ilist_get_size ((MyIList*) self);
				_tmp9_ = _tmp8_;
				if (!(_tmp7_ < _tmp9_)) {
					break;
				}
				{
					gint j;
					j = 0;
					{
						gboolean _tmp10_;
						_tmp10_ = TRUE;
						while (TRUE) {
							gboolean _tmp11_;
							gint _tmp13_;
							MyList* _tmp14_;
							gint _tmp15_;
							gint _tmp16_;
							GCompareFunc _tmp17_;
							gpointer* _tmp18_;
							gint _tmp18__length1;
							gint _tmp19_;
							gconstpointer _tmp20_;
							MyList* _tmp21_;
							gint _tmp22_;
							gpointer _tmp23_ = NULL;
							gpointer _tmp24_;
							gint _tmp25_ = 0;
							gboolean _tmp26_;
							_tmp11_ = _tmp10_;
							if (!_tmp11_) {
								gint _tmp12_;
								_tmp12_ = j;
								j = _tmp12_ + 1;
							}
							_tmp10_ = FALSE;
							_tmp13_ = j;
							_tmp14_ = list;
							_tmp15_ = my_ilist_get_size ((MyIList*) _tmp14_);
							_tmp16_ = _tmp15_;
							if (!(_tmp13_ < _tmp16_)) {
								break;
							}
							_tmp17_ = self->priv->cf;
							_tmp18_ = self->priv->array;
							_tmp18__length1 = self->priv->array_length1;
							_tmp19_ = i;
							_tmp20_ = _tmp18_[_tmp19_];
							_tmp21_ = list;
							_tmp22_ = j;
							_tmp23_ = my_ilist_get ((MyIList*) _tmp21_, _tmp22_);
							_tmp24_ = _tmp23_;
							_tmp25_ = _tmp17_ (_tmp20_, _tmp24_);
							_tmp26_ = _tmp25_ < 0;
							((_tmp24_ == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (_tmp24_ = (self->priv->g_destroy_func (_tmp24_), NULL));
							if (_tmp26_) {
								MyList* _tmp27_;
								gint _tmp28_;
								gpointer* _tmp29_;
								gint _tmp29__length1;
								gint _tmp30_;
								gconstpointer _tmp31_;
								_tmp27_ = list;
								_tmp28_ = j;
								_tmp29_ = self->priv->array;
								_tmp29__length1 = self->priv->array_length1;
								_tmp30_ = i;
								_tmp31_ = _tmp29_[_tmp30_];
								my_ilist_insert ((MyIList*) _tmp27_, _tmp28_, _tmp31_);
								break;
							} else {
								gint _tmp32_;
								MyList* _tmp33_;
								gint _tmp34_;
								gint _tmp35_;
								_tmp32_ = j;
								_tmp33_ = list;
								_tmp34_ = my_ilist_get_size ((MyIList*) _tmp33_);
								_tmp35_ = _tmp34_;
								if (_tmp32_ == (_tmp35_ - 1)) {
									c = 1;
								}
								continue;
							}
						}
					}
				}
				_tmp36_ = c;
				if (_tmp36_ == 1) {
					MyList* _tmp37_;
					gpointer* _tmp38_;
					gint _tmp38__length1;
					gint _tmp39_;
					gconstpointer _tmp40_;
					_tmp37_ = list;
					_tmp38_ = self->priv->array;
					_tmp38__length1 = self->priv->array_length1;
					_tmp39_ = i;
					_tmp40_ = _tmp38_[_tmp39_];
					my_ilist_add ((MyIList*) _tmp37_, _tmp40_);
					c = 0;
				}
			}
		}
	}
	_tmp41_ = list;
	_tmp43_ = my_list_to_array (_tmp41_, &_tmp42_);
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
	self->priv->array = _tmp43_;
	self->priv->array_length1 = _tmp42_;
	self->priv->_array_size_ = self->priv->array_length1;
	_g_object_unref0 (list);
}


static void my_list_real_add_range (MyIList* base, gpointer* items, int items_length1) {
	MyList * self;
	gpointer* _tmp0_;
	gint _tmp0__length1;
	self = (MyList*) base;
	_tmp0_ = items;
	_tmp0__length1 = items_length1;
	{
		gpointer* item_collection = NULL;
		gint item_collection_length1 = 0;
		gint _item_collection_size_ = 0;
		gint item_it = 0;
		item_collection = _tmp0_;
		item_collection_length1 = _tmp0__length1;
		for (item_it = 0; item_it < _tmp0__length1; item_it = item_it + 1) {
			gpointer _tmp1_;
			gpointer item = NULL;
			_tmp1_ = ((item_collection[item_it] != NULL) && (self->priv->g_dup_func != NULL)) ? self->priv->g_dup_func ((gpointer) item_collection[item_it]) : ((gpointer) item_collection[item_it]);
			item = _tmp1_;
			{
				gconstpointer _tmp2_;
				_tmp2_ = item;
				my_ilist_add ((MyIList*) self, _tmp2_);
				((item == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (item = (self->priv->g_destroy_func (item), NULL));
			}
		}
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void my_list_real_add_collection (MyIList* base, MyIList* coll) {
	MyList * self;
	self = (MyList*) base;
	g_return_if_fail (coll != NULL);
	{
		MyIList* _tmp0_;
		MyIList* _tmp1_;
		MyIList* _item_list;
		MyIList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _item_size;
		gint _item_index;
		_tmp0_ = coll;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_item_list = _tmp1_;
		_tmp2_ = _item_list;
		_tmp3_ = my_ilist_get_size (_tmp2_);
		_tmp4_ = _tmp3_;
		_item_size = _tmp4_;
		_item_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			MyIList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			gpointer item;
			gconstpointer _tmp11_;
			_tmp5_ = _item_index;
			_item_index = _tmp5_ + 1;
			_tmp6_ = _item_index;
			_tmp7_ = _item_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _item_list;
			_tmp9_ = _item_index;
			_tmp10_ = my_ilist_get (_tmp8_, _tmp9_);
			item = _tmp10_;
			_tmp11_ = item;
			my_ilist_add ((MyIList*) self, _tmp11_);
			((item == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (item = (self->priv->g_destroy_func (item), NULL));
		}
		_g_object_unref0 (_item_list);
	}
}


static gpointer my_list_real_get (MyIList* base, gint index) {
	MyList * self;
	gpointer result = NULL;
	gpointer* _tmp0_;
	gint _tmp0__length1;
	gint _tmp1_;
	gconstpointer _tmp2_;
	gpointer _tmp3_;
	self = (MyList*) base;
	_tmp0_ = self->priv->array;
	_tmp0__length1 = self->priv->array_length1;
	_tmp1_ = index;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = ((_tmp2_ != NULL) && (self->priv->g_dup_func != NULL)) ? self->priv->g_dup_func ((gpointer) _tmp2_) : ((gpointer) _tmp2_);
	result = _tmp3_;
	return result;
}


static void my_list_real_set (MyIList* base, gint index, gconstpointer val) {
	MyList * self;
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gpointer* _tmp3_;
	gint _tmp3__length1;
	gint _tmp4_;
	gconstpointer _tmp5_;
	gpointer _tmp6_;
	gpointer _tmp7_;
	self = (MyList*) base;
	_tmp0_ = index;
	_tmp1_ = my_ilist_get_size ((MyIList*) self);
	_tmp2_ = _tmp1_;
	if (_tmp0_ >= _tmp2_) {
		return;
	}
	_tmp3_ = self->priv->array;
	_tmp3__length1 = self->priv->array_length1;
	_tmp4_ = index;
	_tmp5_ = val;
	_tmp6_ = ((_tmp5_ != NULL) && (self->priv->g_dup_func != NULL)) ? self->priv->g_dup_func ((gpointer) _tmp5_) : ((gpointer) _tmp5_);
	((_tmp3_[_tmp4_] == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (_tmp3_[_tmp4_] = (self->priv->g_destroy_func (_tmp3_[_tmp4_]), NULL));
	_tmp3_[_tmp4_] = _tmp6_;
	_tmp7_ = _tmp3_[_tmp4_];
}


static gboolean my_list_real_contains (MyIList* base, gconstpointer item) {
	MyList * self;
	gboolean result = FALSE;
	gconstpointer _tmp0_;
	gint _tmp1_ = 0;
	self = (MyList*) base;
	_tmp0_ = item;
	_tmp1_ = my_ilist_index_of ((MyIList*) self, _tmp0_);
	if (_tmp1_ == (-1)) {
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


static gint my_list_real_index_of (MyIList* base, gconstpointer item) {
	MyList * self;
	gint result = 0;
	self = (MyList*) base;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gint _tmp3_;
				gint _tmp4_;
				gint _tmp5_;
				GEqualFunc _tmp6_;
				gpointer* _tmp7_;
				gint _tmp7__length1;
				gint _tmp8_;
				gconstpointer _tmp9_;
				gconstpointer _tmp10_;
				gboolean _tmp11_ = FALSE;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = my_ilist_get_size ((MyIList*) self);
				_tmp5_ = _tmp4_;
				if (!(_tmp3_ < _tmp5_)) {
					break;
				}
				_tmp6_ = self->priv->f;
				_tmp7_ = self->priv->array;
				_tmp7__length1 = self->priv->array_length1;
				_tmp8_ = i;
				_tmp9_ = _tmp7_[_tmp8_];
				_tmp10_ = item;
				_tmp11_ = _tmp6_ (_tmp9_, _tmp10_);
				if (_tmp11_) {
					result = i;
					return result;
				}
			}
		}
	}
	result = -1;
	return result;
}


static gint* my_list_real_index_of_all (MyIList* base, gconstpointer item, int* result_length1) {
	MyList * self;
	gint* result = NULL;
	MyList* _tmp0_;
	MyList* list;
	MyList* _tmp15_;
	gint _tmp16_ = 0;
	gpointer* _tmp17_ = NULL;
	gint* _tmp18_;
	gint _tmp18__length1;
	self = (MyList*) base;
	_tmp0_ = my_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL);
	list = _tmp0_;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_;
				gint _tmp4_;
				gint _tmp5_;
				gint _tmp6_;
				GEqualFunc _tmp7_;
				gpointer* _tmp8_;
				gint _tmp8__length1;
				gint _tmp9_;
				gconstpointer _tmp10_;
				gconstpointer _tmp11_;
				gboolean _tmp12_ = FALSE;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = my_ilist_get_size ((MyIList*) self);
				_tmp6_ = _tmp5_;
				if (!(_tmp4_ < _tmp6_)) {
					break;
				}
				_tmp7_ = self->priv->f;
				_tmp8_ = self->priv->array;
				_tmp8__length1 = self->priv->array_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_];
				_tmp11_ = item;
				_tmp12_ = _tmp7_ (_tmp10_, _tmp11_);
				if (_tmp12_) {
					MyList* _tmp13_;
					gint _tmp14_;
					_tmp13_ = list;
					_tmp14_ = i;
					my_ilist_add ((MyIList*) _tmp13_, (gpointer) ((gintptr) _tmp14_));
				}
			}
		}
	}
	_tmp15_ = list;
	_tmp17_ = my_list_to_array (_tmp15_, &_tmp16_);
	_tmp18_ = _tmp17_;
	_tmp18__length1 = _tmp16_;
	if (result_length1) {
		*result_length1 = _tmp18__length1;
	}
	result = _tmp18_;
	_g_object_unref0 (list);
	return result;
}


static void my_list_real_remove_at (MyIList* base, gint index) {
	MyList * self;
	MyList* _tmp0_;
	MyList* list;
	MyList* _tmp13_;
	gint _tmp14_ = 0;
	gpointer* _tmp15_ = NULL;
	self = (MyList*) base;
	_tmp0_ = my_list_new (self->priv->g_type, (GBoxedCopyFunc) self->priv->g_dup_func, self->priv->g_destroy_func, NULL, NULL);
	list = _tmp0_;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_;
				gint _tmp4_;
				gint _tmp5_;
				gint _tmp6_;
				gint _tmp7_;
				gint _tmp8_;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = my_ilist_get_size ((MyIList*) self);
				_tmp6_ = _tmp5_;
				if (!(_tmp4_ < _tmp6_)) {
					break;
				}
				_tmp7_ = i;
				_tmp8_ = index;
				if (_tmp7_ != _tmp8_) {
					MyList* _tmp9_;
					gpointer* _tmp10_;
					gint _tmp10__length1;
					gint _tmp11_;
					gconstpointer _tmp12_;
					_tmp9_ = list;
					_tmp10_ = self->priv->array;
					_tmp10__length1 = self->priv->array_length1;
					_tmp11_ = i;
					_tmp12_ = _tmp10_[_tmp11_];
					my_ilist_add ((MyIList*) _tmp9_, _tmp12_);
				}
			}
		}
	}
	_tmp13_ = list;
	_tmp15_ = my_list_to_array (_tmp13_, &_tmp14_);
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
	self->priv->array = _tmp15_;
	self->priv->array_length1 = _tmp14_;
	self->priv->_array_size_ = self->priv->array_length1;
	_g_object_unref0 (list);
}


static void my_list_real_remove_range (MyIList* base, gint start, gint length) {
	MyList * self;
	self = (MyList*) base;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gint _tmp3_;
				gint _tmp4_;
				gint _tmp5_;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = length;
				if (!(_tmp3_ < _tmp4_)) {
					break;
				}
				_tmp5_ = start;
				my_ilist_remove_at ((MyIList*) self, _tmp5_);
			}
		}
	}
}


static void my_list_real_remove_all (MyIList* base, gconstpointer item) {
	MyList * self;
	self = (MyList*) base;
	while (TRUE) {
		gconstpointer _tmp0_;
		gint _tmp1_ = 0;
		gconstpointer _tmp2_;
		gint _tmp3_ = 0;
		_tmp0_ = item;
		_tmp1_ = my_ilist_index_of ((MyIList*) self, _tmp0_);
		if (!(_tmp1_ > (-1))) {
			break;
		}
		_tmp2_ = item;
		_tmp3_ = my_ilist_index_of ((MyIList*) self, _tmp2_);
		my_ilist_remove_at ((MyIList*) self, _tmp3_);
	}
}


static void my_list_real_remove (MyIList* base, gconstpointer item) {
	MyList * self;
	gconstpointer _tmp0_;
	gint _tmp1_ = 0;
	self = (MyList*) base;
	_tmp0_ = item;
	_tmp1_ = my_ilist_index_of ((MyIList*) self, _tmp0_);
	if (_tmp1_ > (-1)) {
		gconstpointer _tmp2_;
		gint _tmp3_ = 0;
		_tmp2_ = item;
		_tmp3_ = my_ilist_index_of ((MyIList*) self, _tmp2_);
		my_ilist_remove_at ((MyIList*) self, _tmp3_);
	}
}


static gpointer* _vala_array_dup2 (gpointer* self, int length, GBoxedCopyFunc g_dup_func) {
	gpointer* result;
	int i;
	result = g_new0 (gpointer, length);
	for (i = 0; i < length; i++) {
		gpointer _tmp0_;
		_tmp0_ = ((self[i] != NULL) && (g_dup_func != NULL)) ? g_dup_func ((gpointer) self[i]) : ((gpointer) self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


gpointer* my_list_to_array (MyList* self, int* result_length1) {
	gpointer* result = NULL;
	gpointer* _tmp0_;
	gint _tmp0__length1;
	gpointer* _tmp1_;
	gint _tmp1__length1;
	gpointer* _tmp2_;
	gint _tmp2__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->array;
	_tmp0__length1 = self->priv->array_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup2 (_tmp0_, _tmp0__length1, self->priv->g_dup_func) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	return result;
}


static MyIterator* my_list_real_iterator (MyIterable* base) {
	MyList * self;
	MyIterator* result = NULL;
	MyIterator* _tmp0_;
	self = (MyList*) base;
	_tmp0_ = my_iterator_new (self->priv->g_type, (GBoxedCopyFunc) self->priv->g_dup_func, self->priv->g_destroy_func, (MyIList*) self);
	result = _tmp0_;
	return result;
}


void my_list_clear (MyList* self) {
	gpointer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_new0 (gpointer, 0);
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
	self->priv->array = _tmp0_;
	self->priv->array_length1 = 0;
	self->priv->_array_size_ = self->priv->array_length1;
}


static gboolean my_list_real_equals (MyIEquatable* base, GObject* o) {
	MyList * self;
	gboolean result = FALSE;
	GObject* _tmp0_;
	GObject* _tmp1_;
	MyList* _tmp2_;
	MyList* list;
	gint _tmp3_;
	gint _tmp4_;
	MyList* _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	self = (MyList*) base;
	g_return_val_if_fail (o != NULL, FALSE);
	_tmp0_ = o;
	if (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, MY_TYPE_LIST)) {
		result = FALSE;
		return result;
	}
	_tmp1_ = o;
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, MY_TYPE_LIST, MyList));
	list = _tmp2_;
	_tmp3_ = my_ilist_get_size ((MyIList*) self);
	_tmp4_ = _tmp3_;
	_tmp5_ = list;
	_tmp6_ = my_ilist_get_size ((MyIList*) _tmp5_);
	_tmp7_ = _tmp6_;
	if (_tmp4_ != _tmp7_) {
		result = FALSE;
		_g_object_unref0 (list);
		return result;
	}
	{
		gint i;
		i = 0;
		{
			gboolean _tmp8_;
			_tmp8_ = TRUE;
			while (TRUE) {
				gboolean _tmp9_;
				gint _tmp11_;
				gint _tmp12_;
				gint _tmp13_;
				GEqualFunc _tmp14_;
				gpointer* _tmp15_;
				gint _tmp15__length1;
				gint _tmp16_;
				gconstpointer _tmp17_;
				MyList* _tmp18_;
				gint _tmp19_;
				gpointer _tmp20_ = NULL;
				gpointer _tmp21_;
				gboolean _tmp22_ = FALSE;
				gboolean _tmp23_;
				_tmp9_ = _tmp8_;
				if (!_tmp9_) {
					gint _tmp10_;
					_tmp10_ = i;
					i = _tmp10_ + 1;
				}
				_tmp8_ = FALSE;
				_tmp11_ = i;
				_tmp12_ = my_ilist_get_size ((MyIList*) self);
				_tmp13_ = _tmp12_;
				if (!(_tmp11_ < _tmp13_)) {
					break;
				}
				_tmp14_ = self->priv->f;
				_tmp15_ = self->priv->array;
				_tmp15__length1 = self->priv->array_length1;
				_tmp16_ = i;
				_tmp17_ = _tmp15_[_tmp16_];
				_tmp18_ = list;
				_tmp19_ = i;
				_tmp20_ = my_ilist_get ((MyIList*) _tmp18_, _tmp19_);
				_tmp21_ = _tmp20_;
				_tmp22_ = _tmp14_ (_tmp17_, _tmp21_);
				_tmp23_ = !_tmp22_;
				((_tmp21_ == NULL) || (self->priv->g_destroy_func == NULL)) ? NULL : (_tmp21_ = (self->priv->g_destroy_func (_tmp21_), NULL));
				if (_tmp23_) {
					result = FALSE;
					_g_object_unref0 (list);
					return result;
				}
			}
		}
	}
	result = TRUE;
	_g_object_unref0 (list);
	return result;
}


GEqualFunc my_list_get_equal_func (MyList* self) {
	GEqualFunc result;
	GEqualFunc _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->f;
	result = _tmp0_;
	return result;
}


static gint my_list_real_get_size (MyIList* base) {
	gint result;
	MyList* self;
	gpointer* _tmp0_;
	gint _tmp0__length1;
	self = (MyList*) base;
	_tmp0_ = self->priv->array;
	_tmp0__length1 = self->priv->array_length1;
	result = _tmp0__length1;
	return result;
}


static void my_list_class_init (MyListClass * klass) {
	my_list_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MyListPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_my_list_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_my_list_set_property;
	G_OBJECT_CLASS (klass)->finalize = my_list_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_LIST_G_TYPE, g_param_spec_gtype ("g-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_LIST_G_DUP_FUNC, g_param_spec_pointer ("g-dup-func", "dup func", "dup func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_LIST_G_DESTROY_FUNC, g_param_spec_pointer ("g-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_LIST_EQUAL_FUNC, g_param_spec_pointer ("equal-func", "equal-func", "equal-func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_LIST_SIZE, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void my_list_my_ilist_interface_init (MyIListIface * iface) {
	my_list_my_ilist_parent_iface = g_type_interface_peek_parent (iface);
	iface->add = (void (*)(MyIList*, gconstpointer)) my_list_real_add;
	iface->reverse = (void (*)(MyIList*)) my_list_real_reverse;
	iface->insert = (void (*)(MyIList*, gint, gconstpointer)) my_list_real_insert;
	iface->insert_all = (void (*)(MyIList*, gint, gpointer*, int)) my_list_real_insert_all;
	iface->insert_collection = (void (*)(MyIList*, gint, MyIList*)) my_list_real_insert_collection;
	iface->add_range = (void (*)(MyIList*, gpointer*, int)) my_list_real_add_range;
	iface->add_collection = (void (*)(MyIList*, MyIList*)) my_list_real_add_collection;
	iface->get = (gpointer (*)(MyIList*, gint)) my_list_real_get;
	iface->set = (void (*)(MyIList*, gint, gconstpointer)) my_list_real_set;
	iface->contains = (gboolean (*)(MyIList*, gconstpointer)) my_list_real_contains;
	iface->index_of = (gint (*)(MyIList*, gconstpointer)) my_list_real_index_of;
	iface->index_of_all = (gint* (*)(MyIList*, gconstpointer, int*)) my_list_real_index_of_all;
	iface->remove_at = (void (*)(MyIList*, gint)) my_list_real_remove_at;
	iface->remove_range = (void (*)(MyIList*, gint, gint)) my_list_real_remove_range;
	iface->remove_all = (void (*)(MyIList*, gconstpointer)) my_list_real_remove_all;
	iface->remove = (void (*)(MyIList*, gconstpointer)) my_list_real_remove;
	iface->get_size = my_list_real_get_size;
}


static void my_list_my_iterable_interface_init (MyIterableIface * iface) {
	my_list_my_iterable_parent_iface = g_type_interface_peek_parent (iface);
	iface->iterator = (MyIterator* (*)(MyIterable*)) my_list_real_iterator;
}


static void my_list_my_iequatable_interface_init (MyIEquatableIface * iface) {
	my_list_my_iequatable_parent_iface = g_type_interface_peek_parent (iface);
	iface->equals = (gboolean (*)(MyIEquatable*, GObject*)) my_list_real_equals;
}


static void my_list_instance_init (MyList * self) {
	self->priv = MY_LIST_GET_PRIVATE (self);
}


static void my_list_finalize (GObject* obj) {
	MyList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MY_TYPE_LIST, MyList);
	my_list_clear (self);
	self->priv->array = (_vala_array_free (self->priv->array, self->priv->array_length1, (GDestroyNotify) self->priv->g_destroy_func), NULL);
	G_OBJECT_CLASS (my_list_parent_class)->finalize (obj);
}


GType my_list_get_type (void) {
	static volatile gsize my_list_type_id__volatile = 0;
	if (g_once_init_enter (&my_list_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyList), 0, (GInstanceInitFunc) my_list_instance_init, NULL };
		static const GInterfaceInfo my_ilist_info = { (GInterfaceInitFunc) my_list_my_ilist_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo my_iterable_info = { (GInterfaceInitFunc) my_list_my_iterable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo my_iequatable_info = { (GInterfaceInitFunc) my_list_my_iequatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType my_list_type_id;
		my_list_type_id = g_type_register_static (G_TYPE_OBJECT, "MyList", &g_define_type_info, 0);
		g_type_add_interface_static (my_list_type_id, MY_TYPE_ILIST, &my_ilist_info);
		g_type_add_interface_static (my_list_type_id, MY_TYPE_ITERABLE, &my_iterable_info);
		g_type_add_interface_static (my_list_type_id, MY_TYPE_IEQUATABLE, &my_iequatable_info);
		g_once_init_leave (&my_list_type_id__volatile, my_list_type_id);
	}
	return my_list_type_id__volatile;
}


static void _vala_my_list_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MyList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MY_TYPE_LIST, MyList);
	switch (property_id) {
		case MY_LIST_EQUAL_FUNC:
		g_value_set_pointer (value, my_list_get_equal_func (self));
		break;
		case MY_LIST_SIZE:
		g_value_set_int (value, my_ilist_get_size ((MyIList*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_my_list_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MyList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MY_TYPE_LIST, MyList);
	switch (property_id) {
		case MY_LIST_G_TYPE:
		self->priv->g_type = g_value_get_gtype (value);
		break;
		case MY_LIST_G_DUP_FUNC:
		self->priv->g_dup_func = g_value_get_pointer (value);
		break;
		case MY_LIST_G_DESTROY_FUNC:
		self->priv->g_destroy_func = g_value_get_pointer (value);
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



